### ISSUE TITLE
Make a real CLI tool 

### ISSUE THREAD

**Issue by clintoncwolfe** [omniti-labs/ansible-dk#2]
Lay the groundwork for a real CLI tool, which could eventually have several subcommands:

ansible-dk shell-init ...
ansible-dk generate ...
ansible-dk test ...
ansible-dk verify ...

Then remove the bash script that does shell-init now.

**Comment by mbrannigan** [comment]
I'd be more than happy to take a whack at this.  Do you have a preference as far as the language that this would be written in?  I was going to use either ruby (since the project will have one around) or python with using the click module.  I love click, but this would add the requirement for having python and a requirements.txt file around.  This actually might not be a bad idea in the long run because the project will then be able to interface with the Ansible API.

**Comment by clintoncwolfe** [comment]
Have at it, by all means!    As of https://github.com/omniti-labs/ansible-dk/commit/3cb8d53a17490ea542817ec07d6f761ac7a152bf the omnibus build includes both a Ruby and a Python runtime; and a terrible shell script to set the env vars to find them is on the features/hacky-shell-init branch.

If you want click (or any other module), feel free to pull that in.  You may be blocked by #5, but I am working on that literally right now.

This is a goldmine for python module omnibus definitions: https://github.com/DataDog/omnibus-software/tree/master/config/software

I don't really have an opinion as to which language (or rather, I am struggling to remain neutral :) )

**Comment by clintoncwolfe** [comment]
Closed on #56
