### ISSUE TITLE
Include https://github.com/metacloud/molecule?

### ISSUE THREAD

**Issue by dhutty** [omniti-labs/ansible-dk#40]
Would you be interested in including support for [Molecule](https://github.com/metacloud/molecule) as an additional alternative to test-kitchen? Molecule, unlike kitchen, is specifically aimed at testing Ansible roles and is therefore able to be free of some baggage coming from the Chef history.

**Comment by clintoncwolfe** [comment]
Hey, thanks for pointing that out - I hadn't heard of it, since I come from a ruby/chef/test-kitchen background.  It looks great, and easy to pull in with a pip-based omnibus software definition.  

I should have some cycles next week; if you want it faster, a PR would be welcome - just add something like this - https://github.com/omniti-labs/ansible-dk/commit/130506c8dd259a1f6a39dd4f1652c37ddddf3efc - and we can test it out and package it.

**Comment by clintoncwolfe** [comment]
Thanks!
